### ISSUE TITLE
TypeError: Request path contains unescaped characters

### ISSUE THREAD

**Issue by guan-wy** [teambition/cdn-uploader#6]

**Comment by nekolab** [comment]
Wow, thanks for your feedback

Fixed in https://github.com/teambition/cdn-uploader/commit/26cfcb89a567ee7f78fc4d466f4f28a7591a5e3e

[v0.3.4](https://github.com/teambition/cdn-uploader/releases/tag/v0.3.4) has been published

Feel free to comment or reopen this issue if you have more questions
